# Generated by Django 2.2.1 on 2019-06-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ushort', '0004_auto_20190612_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='hash',
            field=models.CharField(max_length=62, null=True, unique=True),
        ),
    ]
